image: fedora:latest

before_script:
  - dnf install -y llvm-devel git gcc gcc-c++ make findutils gawk
  - git submodule update --init --recursive

install:
  script:
  - make PREFIX=/tmp/xl/ install

install-opt:
  script:
  - make PREFIX=/tmp/xl-opt/ install-opt

install-debug:
  script:
  - make PREFIX=/tmp/xl-debug/ install-debug

install-release:
  script:
  - make PREFIX=/tmp/xl-release/ install-release

test:
  script:
  - make test

test-opt:
  script:
  - make test-opt

test-release:
  script:
  - make test-release

test-debug:
  script:
  - make test-debug

build:
  script:
  - make

build-opt:
  script:
  - make opt

build-debug:
  script:
  - make opt-debug

build-release:
  script:
  - make opt-release
