before_script:
  - dnf install -y llvm-devel git gcc gcc-c++ make findutils gawk || (apt-get update && apt-get install -y llvm-dev git gcc g++ make findutils gawk)
  - git submodule update --init --recursive

install:fedora:
  image: fedora:latest
  script:
  - make PREFIX=/tmp/xl/ install

install-opt:fedora:
  image: fedora:latest
  script:
  - make PREFIX=/tmp/xl-opt/ install-opt

install-debug:fedora:
  image: fedora:latest
  script:
  - make PREFIX=/tmp/xl-debug/ install-debug

install-release:fedora:
  image: fedora:latest
  script:
  - make PREFIX=/tmp/xl-release/ install-release

test:fedora:
  image: fedora:latest
  script:
  - make test

test-opt:fedora:
  image: fedora:latest
  script:
  - make test-opt

test-release:fedora:
  image: fedora:latest
  script:
  - make test-release

test-debug:fedora:
  image: fedora:latest
  script:
  - make test-debug

build:fedora:
  image: fedora:latest
  script:
  - make

build-opt:fedora:
  image: fedora:latest
  script:
  - make opt

build-debug:fedora:
  image: fedora:latest
  script:
  - make opt-debug

build-release:fedora:
  image: fedora:latest
  script:
  - make opt-release

install:ubuntu:
  image: ubuntu:latest
  script:
  - make PREFIX=/tmp/xl/ install

install-opt:ubuntu:
  image: ubuntu:latest
  script:
  - make PREFIX=/tmp/xl-opt/ install-opt

install-debug:ubuntu:
  image: ubuntu:latest
  script:
  - make PREFIX=/tmp/xl-debug/ install-debug

install-release:ubuntu:
  image: ubuntu:latest
  script:
  - make PREFIX=/tmp/xl-release/ install-release

test:ubuntu:
  image: ubuntu:latest
  script:
  - make test

test-opt:ubuntu:
  image: ubuntu:latest
  script:
  - make test-opt

test-release:ubuntu:
  image: ubuntu:latest
  script:
  - make test-release

test-debug:ubuntu:
  image: ubuntu:latest
  script:
  - make test-debug

build:ubuntu:
  image: ubuntu:latest
  script:
  - make

build-opt:ubuntu:
  image: ubuntu:latest
  script:
  - make opt

build-debug:ubuntu:
  image: ubuntu:latest
  script:
  - make opt-debug

build-release:ubuntu:
  image: ubuntu:latest
  script:
  - make opt-release
