image: fedora:latest

before_script:
  - dnf install -y llvm-devel git gcc gcc-c++
  - git submodule update --init --recursive

test:
  script:
  - make PREFIX=/tmp/xl/
  - make PREFIX=/tmp/xl/ install
  - export PATH=$PATH:/tmp/xl/bin
  - make test

make_only:
  script:
  - make
  - make opt
  - make release
  - make debug
